[project]
name = "csv-profiler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "streamlit>=1.52.2",
    "typer>=0.20.1",
]
[project.scripts]
csv-profiler = "csv_profiler.cli:app"

